Update tab component
fullfacing/fng-web-design-system pull request #95
Opened 2021-01-28 15:48 UTC by developerstew

## Description

Update styling to match prototype of Capabilities modal

## Related tickets

Any Jira tickets related to the changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have lint my changes locally.
- [ ] I have formatted my changes locally.
- [ ] I have updated any relevant documentation.
- [ ] I have added tests to cover my changes.
- [ ] I have checked that all new and existing tests passed.
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change.

2021-01-28 15:59 UTC, mantonides requested changes

2021-01-28 15:59 UTC, mantonides commented on src/components/tabs/index.js
> +					hasMarginLeft && styles.MarginLeft,
Please rather use the  object-notation to dynamically assign classes. Eg: 
```
{
  [styles.MarginLeft]: hasMarginLeft
}

2021-01-28 15:59 UTC, mantonides commented on src/components/tabs/index.js
> +					className={hasSeparator ? styles.Seperator : null}
Same as above

2021-01-28 15:59 UTC, mantonides commented on src/components/tabs/index.module.css
> +  opacity: 0.7;
Why do we use opacity here and not in the `background-color` above? Is it not the same as 
```
background-color: var(--color-light3-80);
```
And do we use 0.7 opacity in the designs?

2021-01-28 15:59 UTC, mantonides commented on src/components/tabs/index.module.css
> +  font-weight: 200;
We only use 400, 600 and 700 for font-weight if I am not mistaken

2021-01-29 08:03 UTC, mantonides submitted a review, later dismissed

2021-01-30 08:59 UTC, tiaanduplessis requested changes

2021-01-30 08:59 UTC, tiaanduplessis commented on src/components/tabs/index.js
> +	hasMarginLeft,
It would be a better component API and prevent pollution if these boolean styling flags are removed in favor of using a className. Then the composition of additional styles can be done at a project level if required. Since these once of style changes aren't significant enough to justify a variant of the component to be introduced.

2021-01-30 08:59 UTC, tiaanduplessis commented on src/components/tabs/index.module.css
> +  font-weight: 400;
Isn't this the default applied font-weight 400?

2021-01-30 08:59 UTC, tiaanduplessis commented on src/components/tabs/index.module.css
> +  font-weight: 400;
Same as above

2021-02-01 08:39 UTC, mantonides approved these changes

2021-02-01 08:39 UTC, mantonides commented on src/components/tabs/index.js
>  	hasSeparator,
Can this be removed as well?

2021-02-01 08:42 UTC, developerstew commented on src/components/tabs/index.js
>  	hasSeparator,
Yup sorry

2021-02-01 09:00 UTC, Zazzzles requested changes

2021-02-01 09:00 UTC, Zazzzles commented on src/components/tabs/index.js
> +				className={cn(mixins.FlexAlignCenter, classes.Tablist, {
Are you removing the dynamic styling for vertical tab separator here? Does this tabs component still work as expected in both vertical and horizontal orientation?

2021-02-01 09:05 UTC, Zazzzles requested changes

2021-02-01 09:05 UTC, Zazzzles commented on src/components/tabs/index.js
> +					className={cn(classes.TabPanel)}
Could we rather use lowercase for the keys on the custom styles passed in on the `classes` prop

2021-02-01 09:12 UTC, developerstew commented on src/components/tabs/index.js
> +				className={cn(mixins.FlexAlignCenter, classes.Tablist, {
Yes it is still working as expected. Only difference when alligning vertically would be to change locally: 

.MainTabPanel {
  border-top: 1px solid var(--color-dark1-30);   ==> **Changes to border-left**
}

2021-02-01 09:13 UTC, tiaanduplessis submitted a review, later dismissed

2021-02-01 09:37 UTC, mantonides approved these changes

2021-02-02 07:53 UTC, Zazzzles approved these changes

2021-02-02 07:53 UTC, merged