fix: add checkbox to select all records
fullfacing/fng-web-design-system pull request #98
Opened 2021-02-02 11:11 UTC by mantonides

## Description

 - Add checkbox to select all records
 - Add story for empty table
 - Fix dialog back functionality

## Related tickets

https://fullfacingpty.atlassian.net/browse/IFINGS-5205

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have lint my changes locally.
- [x] I have formatted my changes locally.
- [ ] I have updated any relevant documentation.
- [ ] I have added tests to cover my changes.
- [ ] I have checked that all new and existing tests passed.
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change.

2021-02-02 12:49 UTC, developerstew approved these changes

2021-02-02 18:34 UTC, tiaanduplessis requested changes

2021-02-02 18:34 UTC, tiaanduplessis commented on src/components/checkbox/index.module.css
> +  height: 0px;
px can be omitted for 0

2021-02-02 18:34 UTC, tiaanduplessis commented on src/components/checkbox/index.js
> +				className={styles.CheckboxInput}
for the sake of extension, you might want to contact the classname that is provided as a prop here

2021-02-03 05:31 UTC, developerstew approved these changes

2021-02-03 08:10 UTC, MikeyAlmighty commented on src/components/confirm-dialog/index.js
> +		if (cancelEvent === 'back') return Router.back();
[suggestion] Declare as const above `const BACK = 'back'`

2021-02-03 08:11 UTC, MikeyAlmighty approved these changes

2021-02-03 10:19 UTC, MikeyAlmighty approved these changes

2021-02-03 13:29 UTC, tiaanduplessis approved these changes

2021-02-03 13:29 UTC, merged